version: "3.9"
services:
  api:
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./e2e:/app/e2e:ro

  mongodb:
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
