version: "3.9"
services:
  frontend:
    image: nschnierer/digital-peaks-web-aoa-frontend:latest
    environment:
      - NODE_ENV
      - API_URL
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - default
    depends_on:
      - mongodb
  api:
    image: nschnierer/digital-peaks-web-aoa-api:latest
    container_name: "api"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["$API_COMMAND"]
    environment:
      - EXPRESS_PORT=9000
      - NODE_ENV
      - MONGODB_CONNECTION_STRING
      - JWT_SECRET
      - API_KEY
      - MAX_UPLOAD_FILE_SIZE_MB
      - API_URL
    ports:
      - "${API_PORT:-9000}:9000"
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./r:/app/r
      - ./jobs:/app/jobs
    networks:
      - default
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      # will be used by the init-mongo.js file
      - MONGO_INITDB_API_USERNAME
      - MONGO_INITDB_API_PASSWORD
    volumes:
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./mongo/volume:/data/db
    networks:
      - default

  migration:
    profiles:
      - migration
    image: node:16-alpine
    container_name: "migration"
    restart: always
    command: ["/migration/create-user.js"]
    environment:
      - API_HOST=api
      - API_PORT
      - API_KEY
    volumes:
      - ./migration/create-user.js:/migration/create-user.js:ro
    networks:
      - default
    depends_on:
      - api

networks:
  default:
    driver: bridge
